version: '3.6'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${OUTER_DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
volumes:
  pgdata: